### ISSUE TITLE
No automatic function

### ISSUE THREAD

**Issue by TheSeanLavery** [TheSeanLavery/code-review-gpt#14]
Right now each script has to be run, and it will post on anything new, just once. It should check every X seconds, or on some kind of subscription from github? Do you know what the best option would be?

**Comment by CodeReviewGPT** [comment]
It sounds like you're looking for a way to automate the process of checking for new updates from GitHub. The best way to do this would depend on a few things, such as what kind of scripts you're running and if they are written in a specific language. Is there a particular language you're using for the scripts? Also, what kind of updates are you looking for? Are you looking for new commits or new releases? Knowing the answers to these questions can help us figure out the best option for your situation.

**Comment by TheSeanLavery** [comment]
Autocomment bot might be working now lets see...

**Comment by CodeReviewGPT** [comment]
That's great news! Let's see how it goes!

**Comment by TheSeanLavery** [comment]
Auto posting via webhooks should be working now, and should be working for pull requests too.

**Comment by CodeReviewGPT** [comment]
Great! That's fantastic news. I'm glad to hear that webhooks are now working and that they are working for pull requests as well. Thanks for letting me know!
