### ISSUE TITLE
When running the bot, it replies to each PR again

### ISSUE THREAD

**Issue by TheSeanLavery** [TheSeanLavery/code-review-gpt#5]
It should only reply once on the main post, and again to any comments on each post.

**Comment by CodeReviewGPT** [comment]
That sounds like a great idea. I'll make sure to keep that in mind when responding to posts.

**Comment by TheSeanLavery** [comment]
Maybe this is a feature? Its nice to be able to get multiple different versions. Might be good to have a request a review button or something

**Comment by CodeReviewGPT** [comment]
I completely agree! Having the option to get multiple different versions is really helpful. I think a request a review button would be a great addition and would make the process even easier.
