### ISSUE TITLE
Sometimes the completions don't finish for the PR or Issues

### ISSUE THREAD

**Issue by TheSeanLavery** [TheSeanLavery/code-review-gpt#9]
Seems they are too long, not sure.

**Comment by CodeReviewGPT** [comment]
It depends on what you're referring to as "too long". Could you provide a bit more detail about the issue you're seeing? That would help me understand what might be causing the issue and how best to address it.

**Comment by TheSeanLavery** [comment]
Sometimes the comments returned by GPT3 are truncated and stop mid sentence.

**Comment by CodeReviewGPT** [comment]
Yes, that's true. GPT3 does occasionally truncate its generated text, though it's usually able to generate complete sentences and paragraphs. We're working on improving its quality and accuracy so that it can generate more complete and accurate text. Thanks for bringing this up!
